version: "2.0"
services:
  data:
    image: busybox
    volumes:
      - ./basercms:/var/www/html
    working_dir: /var/www
    command: /bin/echo "data container stared"
  web:
    image: nginx:1.11
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ./containers/web/default.conf.template:/etc/nginx/conf.d/default.conf.template
    volumes_from:
      - data
    environment:
      - NGINX_HOST=basercms.local
      - NGINX_PORT=80
      - NGINX_ROOT=/var/www/html/app/webroot
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_ROOT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  app:
    build: ./containers/app
    network_mode: host
    ports:
      - "9000:9000"
    volumes_from:
      - data
    working_dir: /var/www/html
  db:
    image: mysql:5.6
    network_mode: host
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: basercms_user
      MYSQL_PASSWORD: basercms
      MYSQL_DATABASE: basercms

volumes:
  db-data:
    driver: local

